# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# variables:
#   configuration_debug: Debug
#   configuration_release: Release

strategy:
  matrix:
    mac_1:
      imageName: "macos-10.13"
      build_type: Debug
    mac_2:
      imageName: "macos-10.13"
      build_type: Release
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
- script: brew update
  displayName: 'Update homebrew'

- script: brew install openssl gnutls nettle
  displayName: 'Install OpenSSL'

# Build with the CMake cross-platform build system
- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '../ -DCMAKE_BUILD_TYPE=$(build_type) -DENABLE_UNITTESTS="ON" -DCMAKE_PREFIX_PATH=/usr/local/opt/openssl'
  displayName: 'Super cmake'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '--build ./'