# SRT core build pipeline

trigger:
- master

variables:
  workingDirectory: build
  configurationDebug: Debug
  configurationRelease: Release

jobs:
# - template: templates/npm-with-params.yml  # Template reference
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-16.04'

- template: templates/macOS-job.yml
  parameters:
    name: macOS_debug
    vmImage: 'macOS-10.13'
    buildType: $(configurationDebug)

- template: templates/macOS-job.yml
  parameters:
    name: macOS_release
    vmImage: 'macOS-10.13'
    buildType: $(configurationRelease)

# - template: templates/npm-with-params.yml  # Template reference
#   parameters:
#     name: Windows
#     vmImage: 'vs2017-win2016'