# SRT core build pipeline

trigger:
- master

variables:
  workingDirectory: build
  configurationDebug: Debug
  configurationRelease: Release

strategy:
  matrix:
    1:
      build_type: $(configurationDebug)
    2:
      build_type: $(configurationRelease)
  maxParallel: 2

pool:
  vmImage: "macos-10.13"

steps:
- script: brew update
  displayName: 'Update homebrew'

- script: brew install openssl gnutls nettle
  displayName: 'Install OpenSSL'

- task: CMake@1
  inputs:
    workingDirectory: $(workingDirectory)
    cmakeArgs: '../ -DCMAKE_BUILD_TYPE=$(build_type) -DENABLE_UNITTESTS="ON" -DCMAKE_PREFIX_PATH=/usr/local/opt/openssl'
  displayName: 'Run cmake to create make files'

- task: CMake@1
  inputs:
    workingDirectory: $(workingDirectory)
    cmakeArgs: '--build ./'
  displayName: 'Run cmake to build the project'

- script: ctest --extra-verbose
  workingDirectory: $(workingDirectory)
  displayName: 'Run unit tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'CTest'
    testResultsFiles: '**/TEST-*.xml'