# SRT core build pipeline

trigger:
- master

variables:
  workingDirectory: build
  configurationDebug: Debug
  configurationRelease: Release
  osMacOS: macOS
  osLinux: Linux

jobs:
# - template: templates/template-job.yml
#   parameters:
#     os: $(osMacOS)
#     name: macOS_debug
#     vmImage: 'macOS-10.13'
#     buildType: $(configurationDebug)

- template: templates/macOS-job.yml
  parameters:
    os: $(osMacOS)
    name: macOS_release
    vmImage: 'macOS-10.13'
    buildType: $(configurationRelease)

# - template: templates/template-job.yml
#   parameters:
#     os: $(osMacOS)
#     name: macOS_release_logging
#     vmImage: 'macOS-10.13'
#     buildType: $(configurationRelease)
#     enableLogging: ON

# - template: templates/template-job.yml
#   parameters:
#     os: $(osMacOS)
#     name: macOS_release_heavyLogging
#     vmImage: 'macOS-10.13'
#     buildType: $(configurationRelease)
#     enableHeavyLogging: ON

- template: templates/template-job.yml
  parameters:
    os: $(osLinux)
    name: Linux
    vmImage: 'ubuntu-16.04'

- template: templates/linux-job.yml
  parameters:
    os: $(osLinux)
    name: Linux_2
    vmImage: 'ubuntu-16.04'

# - template: templates/npm-with-params.yml  # Template reference
#   parameters:
#     name: Windows
#     vmImage: 'vs2017-win2016'