# x86_64-w64-mingw32-g++ compiler

parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  workingDirectory: build
  buildType: ''
  enableLogging: OFF
  enableHeavyLogging: OFF

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install gcc-mingw-w64-base
      sudo apt-get install binutils-mingw-w64-x86-64
      sudo apt-get install gcc-mingw-w64-x86-64
      sudo apt-get install gcc-mingw-w64
      sudo apt-get install g++-mingw-w64-x86-64
      # export CC="x86_64-w64-mingw32-gcc"
      # export CXX="x86_64-w64-mingw32-g++"
    displayName: 'Install build dependencies'

  - script: |
      git clone https://github.com/openssl/openssl.git
      cd openssl
      git checkout origin/OpenSSL_1_1_0-stable -b OpenSSL_1_1_0-stable
      ./Configure --cross-compile-prefix=x86_64-w64-mingw32- mingw64
      make
      cd ..
    displayName: 'Install OpenSSL'

  - task: CMake@1
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      cmakeArgs: '../ -DCMAKE_CXX_COMPILER="x86_64-w64-mingw32-g++" -DCMAKE_CC_COMPILER="x86_64-w64-mingw32-gcc" -DCMAKE_BUILD_TYPE=${{ parameters.buildType }} -DENABLE_UNITTESTS="ON" -DENABLE_LOGGING=${{ parameters.enableLogging }} -DENABLE_HEAVY_LOGGING=${{ parameters.enableHeavyLogging }} -DUSE_OPENSSL_PC="OFF" -DOPENSSL_ROOT_DIR="$PWD/openssl" -DCMAKE_SYSTEM_NAME="Windows"'
    displayName: 'Run cmake to create make files'

  - task: CMake@1
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      cmakeArgs: '--build ./'
    displayName: 'Run cmake to build the project'